### ISSUE TITLE
Problem with slf4j libraries

### ISSUE THREAD

**Issue by micheledellaciana1** [knowm/waveforms4j#20]
Hi guys! 
First of all great work. Integration with Java is one of the reasons I took AD2.

I am using the library as downloaded from maven, it works I would say, the only problem is that these lines appear to me during execution:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`

I don't know slf4j, is it a problem? What does it mean?

Thanks in advance for help and continue on this path

Michele

**Comment by timmolter** [comment]
It's not a problem. You just won't get log messages anywhere. You can safely ignore it. If you want to view log messages just read up on SLF4J. Start here: http://www.slf4j.org/codes.html#StaticLoggerBinder

**Comment by micheledellaciana1** [comment]
Perfect! By the way, I'm very interested in this project and by now I'm expanding the DWF class with some utilities that I need for my project. 

I also think it may be worth the effort to write a binder with the same syntax of Arduino. I know that it's not intended for this purpose and it can reduce performances. However, if you load it as a Processing library you can reach many more people!

Sorry to exceed the topic of this issue...

Michele

**Comment by timmolter** [comment]
Very cool. If the utilities have general appeal, please consider submitting a PR! 

I think an Arduino version of this is a great idea, but not something this project wants to invest into and maintain.  You are of course more than welcome to create the project yourself. ;)

**Comment by micheledellaciana1** [comment]
Yes, I'm thinking about it.
Now I'm working to integrate AD2 as an automatic impedance meter for another device for gas sensors characterization, but I'm attracted to do a wrapper very easy to use for an Arduino user!
I'll keep you updated.  

Thk again,

Michele
